### ISSUE TITLE
Use latest version of simphony-common (>=0.2.0)

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-jyulb#27]

**Comment by nathanfranklin** [comment]
@kemattil ,  also it would be good if the required version(s) of simphony are listed in the `setup.py`

**Comment by nathanfranklin** [comment]
@kemattil , is there any update on this work?

**Comment by tuopuu** [comment]
@kemattil, @nathanfranklin I'm working on updating the JyuLB wrapper. It's taking some more time because there's quite a lot of things to change (the wrapper wasn't up to date with some of the earlier releases either). I'm also adopting the new lattice and modelling engine test templates to get rid of some of the duplicated code. Right now I don't have ETA on this, but it could be this week or early next week.

**Comment by nathanfranklin** [comment]
@tuopuu , cool. thanks for the quick response.

**Comment by tuopuu** [comment]
JYU-LB wrapper updated to simphony-common-0.2.2 in #28
